# Generated by Django 3.0.4 on 2020-03-13 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'category_av',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('url', models.FileField(upload_to='docs')),
            ],
            options={
                'db_table': 'file_upload',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='VendorAV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100, unique=True)),
                ('category_av', models.ManyToManyField(related_name='vendors', to='using_api_view.CategoryAV')),
            ],
            options={
                'db_table': 'vendor_av',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryAV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=100, unique=True)),
                ('category_av', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='using_api_view.CategoryAV')),
            ],
            options={
                'db_table': 'sub_category_av',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='using_api_view.Group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='using_api_view.Member')),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='using_api_view.Membership', to='using_api_view.Member'),
        ),
        migrations.CreateModel(
            name='DeliveryAV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField()),
                ('category_av', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='using_api_view.CategoryAV')),
            ],
            options={
                'db_table': 'delivery_av',
            },
        ),
    ]
